#!/usr/bin/env python3
"""
Generate emu2413's tll_table (KSL + TL lookup) as a const C initializer.

This reproduces makeTllTable() from emu2413.c bit-for-bit so the table can be
placed in flash (const) instead of being built in 128 KB of RAM at runtime.
Re-run this if the OPLL tuning constants (EG_STEP, TL2EG, dB2, kl_table) change:

    python3 tools/gen_tll_table.py > smsplus/emu2413/tll_table.h

Reference (emu2413.c):
    #define EG_STEP 0.375
    #define TL2EG(d) ((d) << 1)
    #define dB2(x) ((x)*2)
    static double kl_table[16] = { dB2(0.000), dB2(9.000), ... dB2(21.000) };

    for fnum 0..15, block 0..7, TL 0..63, KL 0..3:
      if KL==0:                tll = TL2EG(TL)
      else:
        tmp = (int32_t)(kl_table[fnum] - dB2(3.000) * (7 - block))
        if tmp <= 0:           tll = TL2EG(TL)
        else:                  tll = (uint32_t)((tmp >> (3-KL)) / EG_STEP) + TL2EG(TL)
"""
import sys

EG_STEP = 0.375
def dB2(x): return x * 2
def TL2EG(d): return d << 1

kl_table = [dB2(v) for v in (
    0.000, 9.000, 12.000, 13.875, 15.000, 16.125, 16.875, 17.625,
    18.000, 18.750, 19.125, 19.500, 19.875, 20.250, 20.625, 21.000,
)]

# Index order matches C: tll_table[(block<<4)|fnum][TL][KL]
DIM0, DIM1, DIM2 = 8 * 16, 64, 4
table = [[[0] * DIM2 for _ in range(DIM1)] for _ in range(DIM0)]

def trunc_i32(d):
    """C cast (int32_t)double — truncate toward zero."""
    return int(d)  # Python int() truncates toward zero, matching C for our ranges

maxval = 0
for fnum in range(16):
    for block in range(8):
        for TL in range(64):
            for KL in range(4):
                if KL == 0:
                    val = TL2EG(TL)
                else:
                    tmp = trunc_i32(kl_table[fnum] - dB2(3.000) * (7 - block))
                    if tmp <= 0:
                        val = TL2EG(TL)
                    else:
                        # (tmp >> (3-KL)) is integer arithmetic shift; result /EG_STEP
                        # is double, cast to uint32_t (truncate), then + TL2EG(TL).
                        val = int((tmp >> (3 - KL)) / EG_STEP) + TL2EG(TL)
                table[(block << 4) | fnum][TL][KL] = val
                maxval = max(maxval, val)

assert maxval < 65536, f"max value {maxval} does not fit in uint16_t"

out = sys.stdout
out.write("/* Auto-generated by tools/gen_tll_table.py — do not edit by hand.\n")
out.write("   emu2413 KSL+TL lookup table, pre-computed so it lives in flash\n")
out.write("   (const) instead of 128 KB of RAM. Values fit in uint16_t\n")
out.write(f"   (max = {maxval}); slot->tll is uint16_t so this matches. */\n")
out.write("#ifndef EMU2413_TLL_TABLE_H\n#define EMU2413_TLL_TABLE_H\n\n")
out.write("#include <stdint.h>\n\n")
out.write(f"static const uint16_t tll_table[{DIM0}][{DIM1}][{DIM2}] = {{\n")
for i in range(DIM0):
    out.write("  {\n")
    for j in range(DIM1):
        vals = ",".join(str(table[i][j][k]) for k in range(DIM2))
        out.write(f"    {{{vals}}},\n")
    out.write("  },\n")
out.write("};\n\n#endif /* EMU2413_TLL_TABLE_H */\n")
